config/routes.rb
Rails.application.routes.draw do

  root 'public/homes#top'

  devise_for :creaters, controllers: {
  	sessions: 'creaters/sessions',
  	passwords: 'creaters/passwords',
  	registrations: 'creaters/registrations'
  }

  devise_for :admins, controllers: {
  	sessions:      'admins/sessions',
  	passwords:     'admins/passwords',
  	registrations: 'admins/registrations'
  }

  devise_for :end_users, controllers: {
  	sessions:      'end_users/sessions',
  	passwords:     'end_users/passwords',
  	registrations: 'end_users/registrations'
  }


    namespace :admins do
	    resources :items, only:[:index, :new, :show, :edit, :update, :destroy]
	    resources :orders, only:[:index, :show, :update]
      resources :order_items, only:[:update]
	    resources :end_users, only:[:index, :show, :edit, :update]
	    resources :creaters, only:[:index, :show, :edit, :update]
	    resources :contacts, only:[:index, :show, :update]
	    resources :homes, only:[:index]
    end

    namespace :creaters do
      resources :items, only:[:index, :new, :create, :show, :edit, :update]
      resources :order_items, only:[:index, :show, :update]
      resources :end_users, only:[:show]
      resources :profiles, only:[:show, :edit, :update]
      resources :homes, only:[:index]
    end

  
    scope module: :public do
	  	get 'about' => 'homes#about'
      resources :items, only:[:index, :show] do
        resource :favorites, only:[:create, :destroy]
      end
      resources :favorites, only:[:index]
      resources :end_users, only:[:show]
      resources :carts, only:[:index, :update, :destroy, :create]
      delete 'destroy_all' => 'carts#destroy_all'
      resources :orders, only:[:index, :new, :create, :show]
      post 'comfirm' => 'orders#comfirm'
      get 'complete' => 'orders#complete'
      resources :contacts, only:[:new, :create]
      post 'check' => 'contacts#check'
      get 'thanks' => 'contacts#thanks'
    end

end

app/models/creater.rb
class Creater < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :items

    enum status: { 活動中: 0, 休止中: 1, 退会: 2}
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :creater
	has_many :carts
	has_many :order_items
	has_many :favorites, dependent: :destroy
	attachment :image

	acts_as_taggable

	def favorited_by?(end_user)
    	favorites.where(end_user_id: end_user.id).exists?
    end

	enum status: {販売中: 0, 売り切れ: 1, 予約商品: 2}
end

app/controllers/admins/creaters_controller.rb
class Admins::CreatersController < ApplicationController

	before_action :authenticate_admin!

	def index
		@creaters = Creater.all
	end

	def show
		@creater = Creater.find(params[:id])
	end

	def edit
		@creater = Creater.find(params[:id])
	end

	def update
		@creater = Creater.find(params[:id])
		@creater.update(creater_params)
		redirect_to admins_creater_path(@creater.id)
	end

	private
	def creater_params
		params.require(:creater).permit(:name, :profile, :status)
	end



end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController

	before_action :authenticate_admin!

	def index
		@creaters = Creater.all
		if params[:creater_sort]
			@items = Item.where(creater_id: params[:creater_sort])
			@creater = Creater.find(params[:creater_sort])
		else
			@items = Item.all
		end
	end

	def show
		@item = Item.find(params[:id])
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		@item.update(item_params)
		redirect_to admins_item_path(@item.id)
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy
		redirect_to admins_items_path
	end

	private

	def item_params
		params.require(:item).permit(:name, :body, :price, :status, :tag_list, :image_id, :creater_id)
	end
end

app/controllers/creater/confirmations_controller.rb
# frozen_string_literal: true

class Creater::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/creater/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Creater::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/creater/passwords_controller.rb
# frozen_string_literal: true

class Creater::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/creater/registrations_controller.rb
# frozen_string_literal: true

class Creater::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/creater/sessions_controller.rb
# frozen_string_literal: true

class Creater::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/creater/unlocks_controller.rb
# frozen_string_literal: true

class Creater::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/creaters/confirmations_controller.rb
# frozen_string_literal: true

class Creaters::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/creaters/end_users_controller.rb
class Creaters::EndUsersController < ApplicationController
end

app/controllers/creaters/homes_controller.rb
class Creaters::HomesController < ApplicationController

	before_action :authenticate_creater!

	def index
		@order_item_news = OrderItem.joins(:item).select("order_items.*, items.*").where(items: {creater_id: current_creater.id}).where(creat_status: "未着手")

		@order_item_goings = OrderItem.joins(:item).select("order_items.*, items.*").where(items: {creater_id: current_creater.id}).where(creat_status: "製作中")
		@item = Item.all
	end
end

app/controllers/creaters/items_controller.rb
class Creaters::ItemsController < ApplicationController

	before_action :authenticate_creater!
	
	def index
		@items = Item.where(creater_id: current_creater.id)
	end

	def new
		@item = Item.new
	end

	def create
		@item = Item.new(item_params)
		@item.save
		redirect_to creaters_item_path(@item.id)
	end

	def show
		@item = Item.find(params[:id])
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		@item.update(item_params)
		redirect_to creaters_item_path(@item.id)
	end

	private

	def item_params
		params.require(:item).permit(:name, :body, :creater_id, :price, :status, :image, :tag_list)
	end
end

app/controllers/creaters/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Creaters::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/creaters/order_items_controller.rb
class Creaters::OrderItemsController < ApplicationController

	before_action :authenticate_creater!

	def index
		@order_items = OrderItem.joins(:item).select("order_items.*, items.*").where(items: {creater_id: current_creater.id}).where(creat_status: "未着手")
	end

	def show
		@order_item = OrderItem.find(params[:id])
		@item = @order_item.item
	end

	def update
		@order_item = OrderItem.find(params[:id])
		@order = @order_item.order
		@order_item.update(order_item_params)

		if @order_item.creat_status == "製作中"
			new_status = "製作中"
			@order.update_attribute(:status, new_status)
		elsif @order.order_items.count == @order.order_items.where(creat_status: "製作完了").count
			new_status = "発送準備中"
			@order.update_attribute(:status, new_status)
		else
		end

		redirect_to creaters_order_items_path
	end

	private

	def order_item_params
		params.require(:order_item).permit(:creat_status)
	end
end

app/controllers/creaters/passwords_controller.rb
# frozen_string_literal: true

class Creaters::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/creaters/profiles_controller.rb
class Creaters::ProfilesController < ApplicationController

	before_action :authenticate_creater!

	def show
	end

	def edit
		@creater = current_creater
	end

	def update
		@creater = current_creater
		@creater.update(creater_params)
		redirect_to creaters_profile_path(@creater.id)
	end

	private

	def creater_params
		params.require(:creater).permit(:name, :profile, :status)
	end
end

app/controllers/creaters/registrations_controller.rb
# frozen_string_literal: true

class Creaters::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/creaters/sessions_controller.rb
# frozen_string_literal: true

class Creaters::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/views/creaters/items/edit.html.erb
<div class="conteinar">
	<div class="row">
		<div class="col-xs-2"></div>
		<div class="col-xs-10">
			<h4>商品新規登録</h4>
	    </div>
	</div>
	<div class="row">
	  	<div class="form-horizontal" role="form">
	  		<%= form_for(@item, url: creaters_item_path(@item.id)) do |f| %>
	  	<div class="col-xs-2"></div>
	    <div class="col-xs-3">
		    <div class="form-group">
				<label>写真</label>
				<p><%= f.attachment_field :image %></p>
			</div>
		</div>

		<div class="col-xs-5">

			<div class="form-group">
				<label class="col-sm-3 control-label">商品名</label>
				<%= f.text_field :name, class:"col-sm-9" %>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">商品説明</label>
				<p><%= f.text_area :body, class:"col-sm-9" %></p>
			</div>
			<div class="form-group">
			    <label class="col-sm-3 control-label">タグ</label>
			    <%= f.text_area :tag_list, value: @item.tag_list, class:"col-sm-9" %>
			</div>
			<div class="col-sm-9 col-sm-offset-3">（半角スペースで区切れます）</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">価格</label>
				<%= f.text_field :price, class:"col-sm-8" %>
				<div class="col-sm-1">円</div>
			</div>
			<div class="form-group">
			  	<label class="col-sm-3 control-label">販売ステータス</label>
			  	<%= f.select :status, Item.statuses.keys{}, {class: 'form-control'} %>
			</div>
			<%= f.hidden_field :creater_id, :value => current_creater.id %>
	    </div>
		<div class="row">
		  <div class="col-xs-9"></div>
		  <div class="col-xs-3">
			<div class="actions">
		    <%= f.submit '変更', class: 'btn btn-default btn-sm' %>
		    </div>
		    <% end %>
		  </div>
	    </div>
	    </div>
	    <div class="col-xs-2"></div>
	</div>
</div>

app/views/creaters/items/index.html.erb
<div class="container">
	<div class="row">
    	<div class="col-md-8 col-md-offset-2">
		<div class="row">
			<div class="col-xs-10">
				<h4>商品一覧</h4>
      		</div>
      		<div class="col-xs-2">
				<%= link_to(new_creaters_item_path) do %>
				<button type="button" class="btn btn-default btn-circle">
				商品追加
			    </button>
				<% end %>
	  		</div>
		</div>
		<table class="table table-hover">
			<thead>
				<tr>
					<th>商品名</th>
					<th>税抜き価格</th>
					<th>販売ステータス</th>
				</tr>
			</thead>
			<tbody>
				<% @items.each do |item| %>
				<tr>
		            <td>
		            	<%= link_to(creaters_item_path(item.id)) do %>
		            	<%= item.name %>
		            	<% end %>
	            	</td>
		            <td><%= item.price %></td>
		            <td><%= item.status %></td>
		        </tr>
			    <% end %>
			</tbody>
		</table>
		</div>
  	</div>
</div>

app/views/creaters/items/new.html.erb
<div class="conteinar">
	<div class="row">
		<div class="col-xs-2"></div>
		<div class="col-xs-10">
			<h4>商品新規登録</h4>
	    </div>
	</div>
	<div class="row">
	  	<div class="form-horizontal" role="form">
	  		<%= form_for(@item, url: creaters_items_path) do |f| %>
	  	<div class="col-xs-2"></div>
	    <div class="col-xs-3">
		    <div class="form-group">
				<label>写真</label>
				<p><%= f.attachment_field :image %></p>
			</div>
		</div>

		<div class="col-xs-5">

			<div class="form-group">
				<label class="col-sm-3 control-label">商品名</label>
				<%= f.text_field :name, class:"col-sm-9" %>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">商品説明</label>
				<%= f.text_area :body, class:"col-sm-9" %>
			</div>
			<div class="form-group">
			    <label class="col-sm-3 control-label">タグ</label>
			    <%= f.text_area :tag_list, value: @item.tag_list, class:"col-sm-9" %>
			</div>
			<div class="col-sm-9 col-sm-offset-3">（半角スペースで区切れます）</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">価格</label>
				<%= f.text_field :price, class:"col-sm-8" %>
				<div class="col-sm-1">円</div>
			</div>
			<div class="form-group">
			  	<label class="col-sm-3 control-label">販売ステータス</label>
			  	<%= f.select :status, Item.statuses.keys{}, {class: 'form-control'} %>
			</div>
			<%= f.hidden_field :creater_id, :value => current_creater.id %>
	    </div>
		<div class="row">
		  <div class="col-xs-9"></div>
		  <div class="col-xs-3">
			<div class="actions">
		    <%= f.submit '投稿', class: 'btn btn-default btn-sm' %>
		    </div>
		    <% end %>
		  </div>
	    </div>
	    </div>
	    <div class="col-xs-2"></div>
	</div>
</div>

app/views/creaters/items/show.html.erb
<div class="container">
  	<div class="row">
		<div class="col-xs-2"></div>
		<div class="col-xs-10">
	  		<h4>商品詳細</h4>
    	</div>
  	</div>
  	<div class="row">
	    <div class="col-xs-2"></div>
	    <div class="col-xs-3">
			<%= attachment_image_tag @item, :image, :fill, 200, 200, format: 'jpeg' %>
	    </div>
	    <div class="col-xs-6">
			<p><strong>商品名</strong>　　　　<%= @item.name %></p>
			<p><strong>商品説明</strong>　　　<%= @item.body %></p>
			<p><strong>tag</strong>          
				<% @item.tag_list.each do |tag| %>
				<span class="btn btn-default btn-xs"><%= tag %></span>
				<% end %>

			<p><strong>価格</strong>　　　    <%= @item.price %>円 </p>
			<p><strong>販売ステータス</strong>　 <%= @item.status %></p>
	    </div>
	  	<div class="col-xs-1"></div>
  	</div>
  	<div class="row">
	    <div class="col-xs-9"></div>
	    <div class="col-xs-3">

			<%= link_to(edit_creaters_item_path(@item.id)) do %>
			<%= button_tag( class: 'btn btn-default' ) do %>
			編集
			<% end %>
			<% end %>
	  	</div>
	</div>
</div>
