config/routes.rb
Rails.application.routes.draw do

  root 'public/homes#top'

  devise_for :creaters, controllers: {
  	sessions: 'creaters/sessions',
  	passwords: 'creaters/passwords',
  	registrations: 'creaters/registrations'
  }

  devise_for :admins, controllers: {
  	sessions:      'admins/sessions',
  	passwords:     'admins/passwords',
  	registrations: 'admins/registrations'
  }

  devise_for :end_users, controllers: {
  	sessions:      'end_users/sessions',
  	passwords:     'end_users/passwords',
  	registrations: 'end_users/registrations'
  }


    namespace :admins do
	    resources :items, only:[:index, :new, :show, :edit, :update, :destroy]
	    resources :orders, only:[:index, :show, :update]
      resources :order_items, only:[:update]
	    resources :end_users, only:[:index, :show, :edit, :update]
	    resources :creaters, only:[:index, :show, :edit, :update]
	    resources :contacts, only:[:index, :show, :update]
	    resources :homes, only:[:index]
    end

    namespace :creaters do
      resources :items, only:[:index, :new, :create, :show, :edit, :update]
      resources :order_items, only:[:index, :show, :update]
      resources :end_users, only:[:show]
      resources :profiles, only:[:show, :edit, :update]
      resources :homes, only:[:index]
    end

  
    scope module: :public do
	  	get 'about' => 'homes#about'
      resources :items, only:[:index, :show] do
        resource :favorites, only:[:create, :destroy]
      end
      resources :favorites, only:[:index]
      resources :end_users, only:[:show]
      resources :carts, only:[:index, :update, :destroy, :create]
      delete 'destroy_all' => 'carts#destroy_all'
      resources :orders, only:[:index, :new, :create, :show]
      post 'comfirm' => 'orders#comfirm'
      get 'complete' => 'orders#complete'
      resources :contacts, only:[:new, :create]
      post 'check' => 'contacts#check'
      get 'thanks' => 'contacts#thanks'
    end

end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :carts, dependent: :destroy
    has_many :orders, dependent: :destroy
    has_many :favorites, dependent: :destroy

end

app/controllers/admins/end_users_controller.rb
class Admins::EndUsersController < ApplicationController

	before_action :authenticate_admin!

	def index
		@end_users = EndUser.all
	end

	def show
		@end_user = EndUser.find(params[:id])
	end

	def edit
		@end_user = EndUser.find(params[:id])
	end

	def update
		@end_user = EndUser.find(params[:id])
		@end_user.update(end_user_params)
		redirect_to admins_end_user_path(@end_user.id)
	end

	private

	def end_user_params
		params.require(:end_user).permit(:name_family, :name_first, :name_family_kana, :name_first_kana, :postal_code, :address, :email, :is_deleted)
	end
end

app/controllers/creaters/end_users_controller.rb
class Creaters::EndUsersController < ApplicationController
end

app/controllers/end_user/confirmations_controller.rb
# frozen_string_literal: true

class EndUser::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/end_user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class EndUser::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/end_user/passwords_controller.rb
# frozen_string_literal: true

class EndUser::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/end_user/registrations_controller.rb
# frozen_string_literal: true

class EndUser::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_user/sessions_controller.rb
# frozen_string_literal: true

class EndUser::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/end_user/unlocks_controller.rb
# frozen_string_literal: true

class EndUser::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users/confirmations_controller.rb
# frozen_string_literal: true

class EndUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/end_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class EndUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/end_users/passwords_controller.rb
# frozen_string_literal: true

class EndUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/end_users/registrations_controller.rb
# frozen_string_literal: true

class EndUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users/sessions_controller.rb
# frozen_string_literal: true

class EndUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/end_users/unlocks_controller.rb
# frozen_string_literal: true

class EndUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/helpers/creaters/end_users_helper.rb
module Creaters::EndUsersHelper
end

app/views/admins/end_users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <div class="row">
        <div class="form-horizontal" role="form">
          <div class="form-group">
            <label class="col-sm-2 control-label">会員ID</label>
            <%= @end_user.id %>
          </div>
          <%= form_for(@end_user, url: admins_end_user_path(@end_user.id)) do |f| %>
          <div class="form-group">
            <label class="col-sm-2 control-label">氏名</label>
                <%= f.text_field :name_family, class:"col-sm-3" %>
                <%= f.text_field :name_first, class:"col-sm-3" %>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">フリガナ</label>
                <%= f.text_field :name_family_kana, class:"col-sm-3" %>
                <%= f.text_field :name_first_kana, class:"col-sm-3" %>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">メールアドレス</label>
                <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"col-sm-6" %>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">郵便番号</label>
                <%= f.text_field :postal_code, class:"col-sm-6" %>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">住所</label>
                <%= f.text_field :address, class:"col-sm-6" %>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">電話番号</label>
                <%= f.text_field :tel, class:"col-sm-6" %>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">会員ステータス</label>
            <label><%= f.radio_button :is_deleted, false %>会員</label>
            <label><%= f.radio_button :is_deleted, true %>退会済み</label>
          </div>

          <div class="actions">
                <%= f.submit "変更を保存する", class:"btn btn-default" %>
          </div>
          <% end %>
    </div>
  </div>
</div>

app/views/admins/end_users/index.html.erb
<div class="container">
  <div class="row">
	<div class="col-xs-6 col-xs-offset-3">
		<h3>会員一覧</h3>
		<table class="table table-hover">
			<thead>
				<tr>
					<th>会員id</th>
					<th>名前</th>
					<th>ステータス</th>
				</tr>
			</thead>
			<tbody>
				<% @end_users.each do |end_user| %>
				<tr>
					<td><%= end_user.id %></td>
					<td>
						<%= link_to(admins_end_user_path(end_user.id)) do %>
						<%= end_user.name_family %><%= end_user.name_first %>
						<% end %>
					</td>
					<td>
						<% if end_user.is_deleted == false %>
						有効会員
						<% else %>
						退会済み
						<% end %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
  </div>
</div>

app/views/admins/end_users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h4><%= @end_user.name_family %><%= @end_user.name_first %>様の会員詳細</h4>
			  <br>
			  <br>
			  <div class="row">
			  	<div class="col-xs-2">
				  <p>顧客ID</p>
				</div>
				<div class="col-xs-10">
				  <%= @end_user.id %>
				  <% if@end_user.is_deleted == false %>
				  <%= button_tag( class: 'btn btn-info btn-xs' ) do %>
				    有効会員
				  <% end %>
				  <% end %>

				</div>
			  </div>
			  <div class="row">
			  	<div class="col-xs-2">
				  <p>氏名</p>
				</div>
				<div class="col-xs-10">
				  <%= @end_user.name_family %><%= @end_user.name_first %>
				</div>
			  </div>
			  <div class="row">
			  	<div class="col-xs-2">
				  <p>フリガナ</p>
				</div>
				<div class="col-xs-10">
				  <%= @end_user.name_family_kana %><%= @end_user.name_first_kana %>
				</div>
			  </div>
			  <div class="row">
			  	<div class="col-xs-2">
				  <p>郵便番号</p>
				</div>
				<div class="col-xs-10">
				  <%= @end_user.postal_code %>
				</div>
			  </div>
			  <div class="row">
			  	<div class="col-xs-2">
				  <p>住所</p>
				</div>
				<div class="col-xs-10">
				  <%= @end_user.address %>
				</div>
			  </div>
			  <div class="row">
			  	<div class="col-xs-2">
				  <p>電話番号</p>
				</div>
				<div class="col-xs-10">
				  <%= @end_user.tel %>
				</div>
			  </div>
			  <div class="row">
			  	<div class="col-xs-2">
				  <p>メールアドレス</p>
				</div>
				<div class="col-xs-10">
				  <%= @end_user.email %>
				</div>
			  </div>
				<br>
				<br>
				<%= link_to(edit_admins_end_user_path(@end_user.id)) do %>
				<%= button_tag( class: 'btn btn-default' ) do %>
				編集する
				<% end %>
				<% end %>　

				<%= link_to "注文一覧", admins_orders_path(end_user_sort: @end_user.id), class:"btn btn-default" %>

		</div>
	</div>
</div>