config/routes.rb
Rails.application.routes.draw do

  root 'public/homes#top'

  devise_for :creaters, controllers: {
  	sessions: 'creaters/sessions',
  	passwords: 'creaters/passwords',
  	registrations: 'creaters/registrations'
  }

  devise_for :admins, controllers: {
  	sessions:      'admins/sessions',
  	passwords:     'admins/passwords',
  	registrations: 'admins/registrations'
  }

  devise_for :end_users, controllers: {
  	sessions:      'end_users/sessions',
  	passwords:     'end_users/passwords',
  	registrations: 'end_users/registrations'
  }


    namespace :admins do
	    resources :items, only:[:index, :new, :show, :edit, :update, :destroy]
	    resources :orders, only:[:index, :show, :update]
      resources :order_items, only:[:update]
	    resources :end_users, only:[:index, :show, :edit, :update]
	    resources :creaters, only:[:index, :show, :edit, :update]
	    resources :contacts, only:[:index, :show, :update]
	    resources :homes, only:[:index]
    end

    namespace :creaters do
      resources :items, only:[:index, :new, :create, :show, :edit, :update]
      resources :order_items, only:[:index, :show, :update]
      resources :end_users, only:[:show]
      resources :profiles, only:[:show, :edit, :update]
      resources :homes, only:[:index]
    end

  
    scope module: :public do
	  	get 'about' => 'homes#about'
      resources :items, only:[:index, :show] do
        resource :favorites, only:[:create, :destroy]
      end
      resources :favorites, only:[:index]
      resources :end_users, only:[:show]
      resources :carts, only:[:index, :update, :destroy, :create]
      delete 'destroy_all' => 'carts#destroy_all'
      resources :orders, only:[:index, :new, :create, :show]
      post 'comfirm' => 'orders#comfirm'
      get 'complete' => 'orders#complete'
      resources :contacts, only:[:new, :create]
      post 'check' => 'contacts#check'
      get 'thanks' => 'contacts#thanks'
    end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :end_user
	belongs_to :item
end

app/models/contact.rb
class Contact < ApplicationRecord
	enum status: { 未対応: 0, 対応中: 1, 対応完了: 2}
end

app/models/creater.rb
class Creater < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :items

    enum status: { 活動中: 0, 休止中: 1, 退会: 2}
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :carts, dependent: :destroy
    has_many :orders, dependent: :destroy
    has_many :favorites, dependent: :destroy

end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :end_user
	belongs_to :item

end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :creater
	has_many :carts
	has_many :order_items
	has_many :favorites, dependent: :destroy
	attachment :image

	acts_as_taggable

	def favorited_by?(end_user)
    	favorites.where(end_user_id: end_user.id).exists?
    end

	enum status: {販売中: 0, 売り切れ: 1, 予約商品: 2}
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :end_user
	has_many :order_items

	enum payment: { クレジットカード: 0, 銀行振込: 1}
	enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送完了: 4}
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :item
	belongs_to :order

	enum creat_status: { 着手不可: 0, 未着手: 1, 製作中: 2, 製作完了: 3}
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController

	before_action :authenticate_admin!

	def index
		@contacts = Contact.where(status: "未対応")
		@order_news = Order.where(status: "入金待ち")
		@order_ends = Order.where(status: "発送準備中")
	end

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController

	before_action :authenticate_admin!

	def index
		@creaters = Creater.all
		if params[:creater_sort]
			@items = Item.where(creater_id: params[:creater_sort])
			@creater = Creater.find(params[:creater_sort])
		else
			@items = Item.all
		end
	end

	def show
		@item = Item.find(params[:id])
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		@item.update(item_params)
		redirect_to admins_item_path(@item.id)
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy
		redirect_to admins_items_path
	end

	private

	def item_params
		params.require(:item).permit(:name, :body, :price, :status, :tag_list, :image_id, :creater_id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
      case resource
      when EndUser
        root_path
      when Admin
        admins_homes_path
      when Creater
      	creaters_homes_path
      end
    end

    def after_sign_out_path_for(resource)
      root_path
    end



	protected

		def configure_permitted_parameters
			devise_parameter_sanitizer.permit(:sign_up, keys: [:name_first, :name_family, :name_first_kana, :name_family_kana, :postal_code, :address, :tel, :name, :profile])
			devise_parameter_sanitizer.permit(:account_update, keys: [:name_first, :name_family, :name_first_kana, :name_family_kana, :postal_code, :address, :tel, :name, :profile, :status])
		end

end

app/controllers/creaters/items_controller.rb
class Creaters::ItemsController < ApplicationController

	before_action :authenticate_creater!
	
	def index
		@items = Item.where(creater_id: current_creater.id)
	end

	def new
		@item = Item.new
	end

	def create
		@item = Item.new(item_params)
		@item.save
		redirect_to creaters_item_path(@item.id)
	end

	def show
		@item = Item.find(params[:id])
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		@item.update(item_params)
		redirect_to creaters_item_path(@item.id)
	end

	private

	def item_params
		params.require(:item).permit(:name, :body, :creater_id, :price, :status, :image, :tag_list)
	end
end

app/helpers/admins/contacts_helper.rb
module Admins::ContactsHelper
end

app/helpers/admins/creaters_helper.rb
module Admins::CreatersHelper
end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creaters/end_users_helper.rb
module Creaters::EndUsersHelper
end

app/helpers/creaters/homes_helper.rb
module Creaters::HomesHelper
end

app/helpers/creaters/items_helper.rb
module Creaters::ItemsHelper
end

app/helpers/creaters/profiles_helper.rb
module Creaters::ProfilesHelper
end

app/views/admins/items/edit.html.erb
<div class="conteinar">
  <div class="row">
	<div class="col-xs-2"></div>
	<div class="col-xs-10">
	  <h4>商品編集</h4>
    </div>
  </div>
  <div class="row">
  	<div class="form-horizontal" role="form">
  	  <%= form_for(@item, url: admins_item_path(@item.id)) do |f| %>
  	<div class="col-xs-2"></div>
    <div class="col-xs-3">
	   <div class="form-group">
		  <label>写真</label>
			<p><%= f.attachment_field :image %></p>
		 </div>
	</div>

	<div class="col-xs-5">

	  <div class="form-group">
		<label class="col-sm-3 control-label">商品名</label>
		<%= f.text_field :name, class:"col-sm-9" %>
	  </div>
	  <div class="form-group">
		<label class="col-sm-3 control-label">商品説明</label>
		<p><%= f.text_area :body, class:"col-sm-9" %></p>
	  </div>
	  <div class="form-group">
		<label class="col-sm-3 control-label">タグ</label>
		<%= f.text_area :tag_list, value: @item.tag_list, class:"col-sm-9" %>
	  </div>
	  <div class="col-sm-9 col-sm-offset-3">（半角スペースで区切れます）</div>
	  <div class="form-group">
		<label class="col-sm-3 control-label">価格</label>
		<%= f.text_field :price, class:"col-sm-8" %>
		<div class="col-sm-1">円</div>
	  </div>
	  <div class="form-group">
	  	<label class="col-sm-3 control-label">販売ステータス</label>
	  	<%= f.select :status, Item.statuses.keys{}, {class: 'form-control'} %>
	  </div>
    </div>
	<div class="row">
	  <div class="col-xs-9"></div>
	  <div class="col-xs-3">
		<div class="actions">
		<%= link_to "Destroy", admins_item_path(@item), method: :delete, class: "btn btn-danger btn-sm" %>
	    <%= f.submit '変更を保存', class: 'btn btn-default btn-sm' %>
	    </div>
	    <% end %>
	  </div>
    </div>
    </div>
    <div class="col-xs-2"></div>
  </div>
</div>

app/views/admins/items/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>製作者一覧</th>
					</tr>
				</thead>
				<tbody>
					<% @creaters.each do |creater| %>
					<tr>
						<td>
							<%= link_to creater.name, admins_items_path(creater_sort: creater.id) %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<div class="col-lg-9">
		    <div class="row">
				<h2><%= @item_index_title %></h2>
				<table class="table table-hover">					<thead>
						<tr>
							<th>作品名</th>
							<th>製作者</th>
							<th>価格</th>
							<th>販売ステータス</th>
						</tr>
					</thead>
					<tbody>
						<% @items.reverse_each do |item| %>
						<tr>
							<td><%= link_to item.name, admins_item_path(item.id) %></td>
							<td><%= item.creater.name %></td>
							<td><%= item.price %></td>
							<td><%= item.status %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
		    </div>
	    </div>
	</div>
</div>

app/views/admins/items/show.html.erb
<div class="container">
  <div class="row">
	<div class="col-xs-12">
	  <h4>商品詳細</h4>
    </div>
  </div>
  <div class="row">
	  <div class="col-xs-6">
		<%= attachment_image_tag @item, :image, :fill, 400, 400, format: 'jpeg' %>
	  </div>
	  <div class="col-xs-6">
		<p><strong>商品名</strong>               <%= @item.name %></p>
		<p><strong>商品説明</strong>             <%= @item.body %></p>
		<p><strong>価格（税抜き）</strong>        <%= @item.price %></p>
		<p><strong>タグ</strong>       
		<% @item.tag_list.each do |tag| %>
		<span class="btn btn-default btn-xs"><%= tag %></span>
		<% end %>
		</p>
		<p><strong>製作者</strong>               <%= @item.creater.name %></p>
		<p><strong>販売ステータス</strong>          <%= @item.status %></p>
	  </div>
	  <div class="col-xs-1"></div>
  </div>
  <div class="row">
	  <div class="col-xs-9"></div>
	  <div class="col-xs-3">

		<%= link_to "編集する", edit_admins_item_path(@item), class:"btn btn-default" %>
	  </div>
	</div>
</div>
